# Generated by Django 2.1.1 on 2018-09-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='signature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
