# Generated by Django 2.1.1 on 2018-09-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_post_signature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='signature',
        ),
    ]
